server:
  port: 8081   

spring:
  datasource:
    url: jdbc:sqlite:tienda1.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLiteDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
